export enum ErrorCode {
  // Validação de campo (E1-E2)
  REQUIRED_FIELDS_MISSING = 'E1',
  INVALID_IMAGE_FORMAT = 'E2',

  // Usuários (E3-E6)
  EMAIL_OR_CPF_ALREADY_EXISTS = 'E3',
  USER_NOT_FOUND = 'E4',
  INCORRECT_PASSWORD = 'E5',
  ACCOUNT_DEACTIVATED = 'E6',

  // Atividades (E7-E18)
  ALREADY_SUBSCRIBED = 'E7',
  CREATOR_CANNOT_SUBSCRIBE = 'E8',
  ONLY_APPROVED_CAN_CHECKIN = 'E9',
  INCORRECT_CONFIRMATION_CODE = 'E10',
  ALREADY_CHECKED_IN = 'E11',
  CANNOT_SUBSCRIBE_COMPLETED = 'E12',
  CANNOT_CHECKIN_COMPLETED = 'E13',
  ONLY_CREATOR_CAN_EDIT = 'E14',
  ONLY_CREATOR_CAN_DELETE = 'E15',
  ONLY_CREATOR_CAN_APPROVE = 'E16',
  ONLY_CREATOR_CAN_COMPLETE = 'E17',
  CANNOT_UNSUBSCRIBE_AFTER_CHECKIN = 'E18',

  // Autenticação (E19)
  AUTHENTICATION_REQUIRED = 'E19',
}