spring:
datasource:
    url: jdbc:postgresql://localhost:5432/bootcamp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lab:
            non_contextual_creation: true
        format_sql: true
        default_schema: public